"""summarize table

Revision ID: a05e5e98a040
Revises: f546b55e0a18
Create Date: 2025-04-19 23:11:00.443478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05e5e98a040'
down_revision: Union[str, None] = 'f546b55e0a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_summary_game_id_key', 'game_summary', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('game_summary_game_id_key', 'game_summary', ['game_id'])
    # ### end Alembic commands ###
