"""Add link to games and reviews

Revision ID: c4be3441ad47
Revises: 3a23e4256851
Create Date: 2025-02-03 19:21:18.695578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4be3441ad47'
down_revision: Union[str, None] = '3a23e4256851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('link', sa.String(), nullable=True))
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_games_name', table_name='games')
    op.create_unique_constraint(None, 'games', ['name'])
    op.add_column('reviews', sa.Column('link', sa.String(), nullable=True))
    op.alter_column('reviews', 'review_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'review_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('reviews', 'link')
    op.drop_constraint(None, 'games', type_='unique')
    op.create_index('ix_games_name', 'games', ['name'], unique=True)
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('games', 'link')
    # ### end Alembic commands ###
