"""add full-text search index and summarize table

Revision ID: f546b55e0a18
Revises: 1b6b4896f175
Create Date: 2025-04-19 23:08:37.541306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f546b55e0a18'
down_revision: Union[str, None] = '1b6b4896f175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('description_ru', sa.String(), nullable=True))
    op.add_column('games', sa.Column('description_en', sa.String(), nullable=True))
    op.add_column('games', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'search_vector')
    op.drop_column('games', 'description_en')
    op.drop_column('games', 'description_ru')
    # ### end Alembic commands ###
